//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGeneratorUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class source {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal source() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordGeneratorUI.source", typeof(source).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string everything {
            get {
                return ResourceManager.GetString("everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz0123456789.
        /// </summary>
        internal static string lowercase_numbers {
            get {
                return ResourceManager.GetString("lowercase_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string lowercase_numbers_symbols {
            get {
                return ResourceManager.GetString("lowercase_numbers_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string lowercase_symbols {
            get {
                return ResourceManager.GetString("lowercase_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string numbers_symbols {
            get {
                return ResourceManager.GetString("numbers_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz.
        /// </summary>
        internal static string only_lowercase {
            get {
                return ResourceManager.GetString("only_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789.
        /// </summary>
        internal static string only_numbers {
            get {
                return ResourceManager.GetString("only_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string only_symbols {
            get {
                return ResourceManager.GetString("only_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ.
        /// </summary>
        internal static string only_uppercase {
            get {
                return ResourceManager.GetString("only_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.
        /// </summary>
        internal static string upper_lower_numbers {
            get {
                return ResourceManager.GetString("upper_lower_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string upper_lower_symbols {
            get {
                return ResourceManager.GetString("upper_lower_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.
        /// </summary>
        internal static string uppercase_lowercase {
            get {
                return ResourceManager.GetString("uppercase_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
        /// </summary>
        internal static string uppercase_numbers {
            get {
                return ResourceManager.GetString("uppercase_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string uppercase_numbers_symbols {
            get {
                return ResourceManager.GetString("uppercase_numbers_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ`~!@#$%^&amp;*()_-=+/*-.|\}[]{}&quot;&apos;:;?&lt;&gt;,.
        /// </summary>
        internal static string uppercase_symbols {
            get {
                return ResourceManager.GetString("uppercase_symbols", resourceCulture);
            }
        }
    }
}
